services:
  neo4j:
    build: ./graph/
    volumes:
      - neo4jdata:/data
      - neo4jlogs:/logs
      - neo4jplugins:/plugins
    environment:
      
      - NEO4J_server_memory_pagecache_size=1G
      - NEO4J_server_bolt_telemetry_enabled=false
      - NEO4J_client_allow__telemetry=false
      - NEO4J_AUTH=$NEO4J_USERNAME/$NEO4J_PASSWORD
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_server_bolt_advertised__address=localhost:7687
      - NEO4J_server_http_advertised__address=localhost:7474
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - 7474:7474
      - 7687:7687
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
    deploy:
      resources:
        limits:
          cpus: '12'
          memory: 5g
        reservations:
          cpus: '12'
          memory: 5g


  liteollama:
    build: .
    container_name: liteollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
      - "4000:4000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
          cpus: '4'
          memory: 5g
        limits:
          cpus: '4'
          memory: 5g


    entrypoint: /tmp/run_ollama.sh "llama3-groq-tool-use"

volumes:
  ollama:
    external: true
    name: ollama
  neo4jdata:
    driver: local
  neo4jlogs:
    driver: local
  neo4jplugins:
    driver: local

