version: '3.8'

services:
  liteollama:
    build: .
    container_name: liteollama
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"
      - "4000:4000"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    entrypoint: /tmp/run_ollama.sh "llama3-groq-tool-use"

volumes:
  ollama:
    external: true
    name: ollama

